//! 将生成结果注入已有工程入口或注册点，避免手工接线。
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

use crate::generate_types::{CompiledModuleEntry, GeneratedContractPlan, ModuleConfig};
use crate::models::GenerateModuleWorkflowInput;

pub(crate) fn should_inject_modules(
    config: &ModuleConfig,
    input: &GenerateModuleWorkflowInput,
) -> bool {
    if input.no_inject {
        return false;
    }
    // 默认开启注入：除非 config 明确设置 inject.enabled=false。
    config
        .inject
        .as_ref()
        .and_then(|inject| inject.enabled)
        .unwrap_or(true)
}

pub(crate) fn prepare_main_go_injection(
    config: &ModuleConfig,
    input: &GenerateModuleWorkflowInput,
    config_dir: &Path,
    module_dir: &Path,
    all_entries: &[CompiledModuleEntry],
) -> Result<Option<(GeneratedContractPlan, GeneratedContractPlan)>> {
    // “注入”的目标是：让用户工程在不手写接线代码的情况下，
    // 也能把生成的模块注册进自己的启动入口（通常是 main.go）。
    //
    // 注入策略非常保守：
    // - 只有检测到 marker 区间才会改写 main.go
    // - 找不到 marker/找不到 main.go 都不会报错（只是不注入）
    // 这样可以避免生成器破坏用户工程的结构。
    // 目标 main.go 的寻找优先级：CLI 参数 > inject.target_main > framework.main > 默认 main.go。
    let target_main = input
        .main_path
        .clone()
        .or_else(|| {
            config
                .inject
                .as_ref()
                .and_then(|inject| inject.target_main.clone())
        })
        .or_else(|| config.framework.main.clone())
        .unwrap_or_else(|| "main.go".into());
    let target_main = resolve_against_cwd(config_dir, &target_main);
    if !target_main.exists() {
        // 找不到 main 文件时不算错误：模块仍可以生成，只是不做注入。
        return Ok(None);
    }
    let original = std::fs::read_to_string(&target_main)
        .with_context(|| format!("failed to read main.go {}", target_main.display()))?;
    let marker_start = config
        .inject
        .as_ref()
        .and_then(|inject| inject.marker.as_ref())
        .and_then(|marker| marker.start.clone())
        .unwrap_or_else(|| "lania:modules:start".into());
    let marker_end = config
        .inject
        .as_ref()
        .and_then(|inject| inject.marker.as_ref())
        .and_then(|marker| marker.end.clone())
        .unwrap_or_else(|| "lania:modules:end".into());
    let Some(updated_main) = inject_main_go_markers(&original, &marker_start, &marker_end) else {
        // marker 不存在/顺序不合法时不做注入：避免破坏用户已有代码结构。
        return Ok(None);
    };
    let main_package = detect_go_package(&original).unwrap_or_else(|| "main".into());
    // helper 文件使用 `zz_` 前缀与 `.gen.go`：
    // - `zz_` 让它在目录排序里更靠后，降低和业务文件混在一起的“视觉干扰”
    // - `.gen.go` 明确表示生成文件，并便于工具链识别
    let helper_path = target_main
        .parent()
        .unwrap_or(config_dir)
        .join("zz_lania_module_inject.gen.go");
    let import_path = input
        .package_name
        .clone()
        // 未指定包名时，用 module_dir 相对 config_dir 的路径推导 import path（转成 / 分隔）。
        // 这是一种“足够好”的默认：让 init scaffold 或简单工程可以零配置跑通。
        .unwrap_or_else(|| {
            path_to_slash_string(module_dir.strip_prefix(config_dir).unwrap_or(module_dir))
        });
    let helper_body = render_main_go_helper(&main_package, &import_path, all_entries);
    Ok(Some((
        GeneratedContractPlan {
            path: target_main,
            content: updated_main,
            owner: None,
        },
        GeneratedContractPlan {
            path: helper_path,
            content: helper_body,
            owner: None,
        },
    )))
}

pub(crate) fn inject_main_go_markers(
    content: &str,
    marker_start: &str,
    marker_end: &str,
) -> Option<String> {
    let lines = content.lines().collect::<Vec<_>>();
    let start = lines.iter().position(|line| line.contains(marker_start))?;
    let end = lines.iter().position(|line| line.contains(marker_end))?;
    if end <= start {
        return None;
    }
    // 注入点缩进沿用 start marker 所在行的前导空白，以匹配项目风格。
    let indent = lines[start]
        .chars()
        .take_while(|ch| ch.is_ascii_whitespace())
        .collect::<String>();
    let mut updated = Vec::new();
    updated.extend(lines[..=start].iter().map(|line| (*line).to_string()));
    updated.push(format!("{indent}_ = RegisterLaniaGeneratedModules()"));
    updated.extend(lines[end..].iter().map(|line| (*line).to_string()));
    let mut rendered = updated.join("\n");
    if content.ends_with('\n') {
        // 保持原文件末尾换行习惯，避免产生无意义 diff。
        rendered.push('\n');
    }
    Some(rendered)
}

pub(crate) fn render_main_go_helper(
    package_name: &str,
    import_path: &str,
    all_entries: &[CompiledModuleEntry],
) -> String {
    // 这个 helper 的存在主要是解决两个问题：
    // 1) main.go 里避免出现过多生成逻辑（保持入口文件干净）
    // 2) 通过一个“总入口函数”把生成模块列表暴露出来，便于用户按需接入
    let mut body = String::from("// Code generated by lania generate module. DO NOT EDIT.\n\n");
    body.push_str(&format!("package {package_name}\n\n"));
    body.push_str(&format!("import generatedmodules \"{}\"\n\n", import_path));
    body.push_str("func RegisterLaniaGeneratedModules() []string {\n");
    body.push_str("    return generatedmodules.GeneratedModules()\n");
    body.push_str("}\n\n");
    body.push_str("var _ = []string{\n");
    for entry in all_entries {
        body.push_str(&format!("    \"{}\",\n", entry.name));
    }
    body.push_str("}\n");
    body
}

pub(crate) fn detect_go_package(content: &str) -> Option<String> {
    content.lines().map(str::trim).find_map(|line| {
        line.strip_prefix("package ")
            .map(|value| value.trim().to_string())
    })
}

pub(crate) fn path_to_slash_string(path: &Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}

pub(crate) fn resolve_against_cwd(cwd: &Path, raw: &str) -> PathBuf {
    let path = PathBuf::from(raw);
    if path.is_absolute() {
        path
    } else {
        cwd.join(path)
    }
}
