//! Schema 解析与 Go 代码渲染的通用小工具（generate-api 侧）。
//!
//! 这类文件的特点是：
//! - 看起来像“字符串拼接”，但实际承载了非常多协议约定/命名约定；
//! - 一旦改动，输出文件的稳定性（diff 噪音、向后兼容）就会受到影响。
//!
//! 建议新手的阅读方式：
//! 1) 先看 `exported_name/slugify/sanitize_go_type`，理解命名与类型映射
//! 2) 再看 `render_contract_go/render_transport_go`，理解生成物大体结构
//! 3) 最后看 `stable_hash`，理解为何需要“稳定 hash”而不是随机值

use anyhow::{anyhow, Result};

use crate::generate_types::CompiledContractEntry;

pub(crate) fn strip_inline_comment(line: &str) -> &str {
    // proto/thrift 文件里常见 `// comment`，这里把它剥掉，避免 parser 误识别字段。
    line.split("//").next().unwrap_or("")
}

pub(crate) fn render_contract_go(entry: &CompiledContractEntry) -> String {
    // contract.go 只负责“类型 + service interface”：
    // - 让下游业务实现可以按 interface 编译通过
    // - 让 transport 层（grpc/http）有统一的契约入口
    let mut body = String::from("// Code generated by lania generate api. DO NOT EDIT.\n\n");
    if !entry.ir.services.is_empty() {
        body.push_str("package generated\n\nimport \"context\"\n\n");
    } else {
        body.push_str("package generated\n\n");
    }
    if entry
        .ir
        .services
        .iter()
        .flat_map(|service| service.methods.iter())
        .any(|method| method.request == "Empty" || method.response == "Empty")
    {
        body.push_str("type Empty struct {}\n\n");
    }

    for ty in &entry.ir.types {
        body.push_str(&format!("type {} struct {{\n", exported_name(&ty.name)));
        for field in &ty.fields {
            body.push_str(&format!(
                "    {} {} `json:\"{}\"`\n",
                exported_name(&field.name),
                sanitize_go_type(&field.ty),
                field.name
            ));
        }
        body.push_str("}\n\n");
    }

    for service in &entry.ir.services {
        body.push_str(&format!(
            "type {} interface {{\n",
            exported_name(&service.name)
        ));
        for method in &service.methods {
            body.push_str(&format!(
                "    {}(ctx context.Context, req {}) ({}, error)\n",
                exported_name(&method.name),
                sanitize_go_type(&method.request),
                sanitize_go_type(&method.response)
            ));
        }
        body.push_str("}\n\n");
    }

    body
}

pub(crate) fn render_transport_go(entry: &CompiledContractEntry, target: &str) -> Result<String> {
    // transport.go 负责提供“协议侧 wrapper”，但不会生成具体 handler：
    // 它更像一个适配层，把协议事件/请求转成对 interface 的调用。
    let mut body = String::from("// Code generated by lania generate api. DO NOT EDIT.\n\n");
    body.push_str("package generated\n\n");
    for service in &entry.ir.services {
        let service_name = exported_name(&service.name);
        match target {
            "grpc" => {
                body.push_str(&format!(
                    "type {service_name}GrpcHandler struct {{\n    Impl {service_name}\n}}\n\n"
                ));
                for method in &service.methods {
                    body.push_str(&format!(
                        "func (h {service_name}GrpcHandler) {}(req {}) ({}, error) {{\n    return h.Impl.{}(context.Background(), req)\n}}\n\n",
                        exported_name(&method.name),
                        sanitize_go_type(&method.request),
                        sanitize_go_type(&method.response),
                        exported_name(&method.name)
                    ));
                }
            }
            "http" => {
                body.push_str(&format!(
                    "type {service_name}HttpHandler struct {{\n    Impl {service_name}\n}}\n\n"
                ));
                for method in &service.methods {
                    body.push_str(&format!(
                        "func (h {service_name}HttpHandler) {}(req {}) ({}, error) {{\n    return h.Impl.{}(context.Background(), req)\n}}\n\n",
                        exported_name(&method.name),
                        sanitize_go_type(&method.request),
                        sanitize_go_type(&method.response),
                        exported_name(&method.name)
                    ));
                }
            }
            other => return Err(anyhow!("unsupported target kind: {other}")),
        }
    }
    if !entry.ir.services.is_empty() {
        body = body.replacen(
            "package generated\n\n",
            "package generated\n\nimport \"context\"\n\n",
            1,
        );
    }
    Ok(body)
}

pub(crate) fn proto_scalar_to_go(value: &str) -> String {
    // proto scalar -> Go scalar 的映射表。
    // 非 scalar 的类型名会走 `exported_name` 做首字母大写与分段拼接。
    match value {
        "string" => "string".into(),
        "bool" => "bool".into(),
        "bytes" => "[]byte".into(),
        "int32" | "sint32" | "sfixed32" => "int32".into(),
        "int64" | "sint64" | "sfixed64" => "int64".into(),
        "uint32" | "fixed32" => "uint32".into(),
        "uint64" | "fixed64" => "uint64".into(),
        "float" => "float32".into(),
        "double" => "float64".into(),
        other => exported_name(other),
    }
}

pub(crate) fn thrift_scalar_to_go(value: &str) -> String {
    // thrift scalar -> Go scalar 的映射表。
    match value {
        "string" => "string".into(),
        "bool" => "bool".into(),
        "byte" | "i8" => "int8".into(),
        "i16" => "int16".into(),
        "i32" => "int32".into(),
        "i64" => "int64".into(),
        "double" => "float64".into(),
        "binary" => "[]byte".into(),
        other => exported_name(other),
    }
}

pub(crate) fn sanitize_go_type(value: &str) -> String {
    // IR 里的类型字符串比较宽松：
    // - 基本类型（string/int32/...）
    // - 数组 `[]T`
    // - any / []any
    // 这里把它们规范化为 Go 可以编译的类型名。
    if let Some(rest) = value.strip_prefix("[]") {
        return format!("[]{}", sanitize_go_type(rest));
    }
    if let Some(inner) = value.strip_prefix("map[").and_then(|rest| rest.split_once(']')) {
        return format!(
            "map[{}]{}",
            sanitize_go_type(inner.0),
            sanitize_go_type(inner.1)
        );
    }
    match value {
        "string" | "bool" | "int8" | "int16" | "int32" | "int64" | "uint32" | "uint64"
        | "float32" | "float64" | "[]byte" | "any" => value.into(),
        other => exported_name(other.rsplit('.').next().unwrap_or(other)),
    }
}

pub(crate) fn exported_name(value: &str) -> String {
    // 把任意名字转换为 Go 可导出标识符（首字母大写 + 去掉分隔符）。
    // 例如：`hello_world` -> `HelloWorld`，`foo-bar` -> `FooBar`
    value
        .split(|ch: char| !ch.is_ascii_alphanumeric())
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            let first = chars
                .next()
                .map(|ch| ch.to_ascii_uppercase())
                .unwrap_or_default();
            let rest = chars.as_str();
            format!("{first}{rest}")
        })
        .collect::<String>()
}

pub(crate) fn slugify(value: &str) -> String {
    // slug 用于文件名与路径：只保留 [a-z0-9_]，其它字符统一归一化成 `_`。
    let mut slug = String::new();
    let mut last_was_separator = false;
    for ch in value.chars() {
        if ch.is_ascii_alphanumeric() {
            slug.push(ch.to_ascii_lowercase());
            last_was_separator = false;
        } else if !last_was_separator {
            slug.push('_');
            last_was_separator = true;
        }
    }
    slug.trim_matches('_').to_string()
}

pub(crate) fn stable_hash(value: &str) -> u64 {
    // 这里用的是 FNV-1a 的简化实现：
    // - 目的不是密码学安全，而是“对同一输入稳定输出一个 u64”
    // - 常用于生成 stable id、cache key 或输出文件名后缀
    let mut hash = 1469598103934665603u64;
    for byte in value.as_bytes() {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(1099511628211);
    }
    hash
}
