import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';

import { fileExists } from '../../../core/runtime.js';

import { PRODUCT_REPORT_VERSION } from '../constants.js';
import type { ProductGenerateReport } from '../types.js';
import {
  escapeTemplateString,
  firstNonEmptyString,
  normalizeGeneratedBinaryName,
  resolveGeneratedPackageName,
  toPortableRelativePath,
} from '../utils.js';

// `product.generate` scaffolds a minimal product workspace:
// - `package.json` / `lan.config.json`
// - schema entry and a tiny template
// - a README with next steps
//
// This handler intentionally does not invoke other tools; it only writes files.

export async function handleGenerate(params: Record<string, unknown>) {
  const cwd = typeof params.cwd === 'string' ? params.cwd : process.cwd();
  const force = params.force === true;
  const preset = firstNonEmptyString(params.preset) ?? 'demo';

  // We accept multiple param names for compatibility with earlier CLIs.
  const requestedName = firstNonEmptyString(params.name, params.binaryName, params.packageName);
  if (!requestedName) {
    throw new Error(
      'lan generate product requires --name, --binary-name, or --package-name to scaffold a product',
    );
  }

  const binaryName = normalizeGeneratedBinaryName(
    firstNonEmptyString(params.binaryName, requestedName) ?? 'product',
  );
  const packageName = resolveGeneratedPackageName(params.packageName, binaryName);
  const displayName =
    firstNonEmptyString(params.displayName, params.name, requestedName, binaryName) ?? binaryName;

  // Output is relative to cwd by default, but we persist absolute paths in the report for clarity.
  const outputDir = firstNonEmptyString(params.outputDir) ?? join('products', `${binaryName}-cli`);
  const outputRoot = resolve(cwd, outputDir);

  const templateId = preset === 'minimal' ? 'base' : 'demo-app';
  const templateTitle = preset === 'minimal' ? 'Base Template' : 'Demo App';
  const uiOutputMode = preset === 'minimal' ? 'json' : 'human';

  const files = new Map<string, string>([
    [
      join(outputRoot, 'package.json'),
      `${JSON.stringify(
        {
          name: packageName,
          version: '0.1.0',
          private: true,
          type: 'module',
        },
        null,
        2,
      )}\n`,
    ],
    [
      join(outputRoot, 'README.md'),
      createGeneratedProductReadme({
        packageName,
        binaryName,
        displayName,
      }),
    ],
    [
      join(outputRoot, 'lan.config.json'),
      `${JSON.stringify(
        {
          extensions: { dynamicCommands: true },
          ui: { output: { mode: uiOutputMode } },
          tools: {
            allow: ['bridge', 'result', 'log', 'text', 'fs', 'workspace', 'path'],
            fs: { writeRoot: '.' },
            bridge: {
              allowMethods: ['bridge.*', 'config.*', 'template.*', 'product.*'],
            },
          },
          product: {
            name: packageName,
            binaryName,
            displayName,
            templatesDir: './product/templates',
            compat: {
              frameworkVersionRange: '>=0.1.0 <1.0.0',
              protocolVersionRange: '0.1.0',
              nodeBridgeVersionRange: '0.1.0',
            },
          },
          schema: {
            entry: './product/lania.schemas.ts',
          },
        },
        null,
        2,
      )}\n`,
    ],
    [
      join(outputRoot, 'product', 'lania.schemas.ts'),
      createGeneratedProductSchema({
        displayName,
        binaryName,
        templateId,
        templateTitle,
      }),
    ],
    [
      join(outputRoot, 'product', 'templates', templateId, 'template.json'),
      `${JSON.stringify(
        {
          name: templateId,
          schemaVersion: 1,
          renderEngine: 'node_bridge',
          legacyTemplateDir: `product/templates/${templateId}`,
          ownership: 'third_party_extension',
          useCases: ['create'],
        },
        null,
        2,
      )}\n`,
    ],
    [
      join(outputRoot, 'product', 'templates', templateId, 'files', 'README.md.ejs'),
      `# <%= projectName || name || '${escapeTemplateString(displayName)}' %>

Generated by \`${escapeTemplateString(binaryName)}\` (product template: \`${templateId}\`).

\`\`\`bash
# List templates (includes product templates via product.templatesDir)
lan template

# Inspect this template
lan template ${templateId}
\`\`\`
`,
    ],
  ]);

  if (!force) {
    // Preflight check: refuse overwriting to keep the scaffold safe by default.
    for (const filePath of files.keys()) {
      if (await fileExists(filePath)) {
        throw new Error(
          `lan generate product refused to overwrite existing file: ${toPortableRelativePath(outputRoot, filePath)}`,
        );
      }
    }
  }

  await mkdir(join(outputRoot, 'product', 'workflows'), { recursive: true });
  for (const [filePath, content] of files) {
    await mkdir(dirname(filePath), { recursive: true });
    await writeFile(filePath, content, 'utf8');
  }

  const generatedFiles = [
    './package.json',
    './README.md',
    './lan.config.json',
    './product',
    './product/lania.schemas.ts',
    './product/templates',
    `./product/templates/${templateId}`,
    `./product/templates/${templateId}/template.json`,
    `./product/templates/${templateId}/files`,
    `./product/templates/${templateId}/files/README.md.ejs`,
    './product/workflows',
  ];

  const report: ProductGenerateReport = {
    accepted: true,
    reportVersion: PRODUCT_REPORT_VERSION,
    kind: 'product_generate',
    mode: 'scaffold',
    outputRoot,
    checks: {
      hasPackageJson: true,
      hasLanConfig: true,
      hasSchemaEntry: true,
      hasTemplatesDir: true,
    },
    generatedFiles,
    experimental: {
      packageName,
      binaryName,
      displayName,
      preset,
      templateId,
    },
    exitCode: 0,
  };

  return {
    result: report,
    events: [],
  };
}

function createGeneratedProductReadme(input: {
  packageName: string;
  binaryName: string;
  displayName: string;
}): string {
  // README is intentionally short: it should guide the first-time user to a working workflow.
  return `# ${input.displayName}

Generated product scaffold for \`${input.packageName}\`.

Development:

\`\`\`bash
lan product inspect --path .
lan product dev --path . hello
\`\`\`

Distribution:

\`\`\`bash
lan product build
lan product pack
lan product publish
\`\`\`
`;
}

function createGeneratedProductSchema(input: {
  displayName: string;
  binaryName: string;
  templateId: string;
  templateTitle: string;
}): string {
  // The generated schema includes a tiny "hello" workflow plus a template inspection workflow.
  // It is primarily used by tests and as an example for authors.
  return `export default {
  commands: [
    {
      name: 'hello',
      about: 'Verify the generated product scaffold',
      workflow: 'hello',
    },
    {
      name: 'product-template',
      about: 'Inspect templates (builtin + product templates)',
      workflow: 'productTemplate',
    },
  ],
  workflows: {
    async hello(ctx) {
      return {
        result: {
          message: 'hello from ${escapeTemplateString(input.displayName)}',
          binaryName: '${escapeTemplateString(input.binaryName)}',
          workspaceRoot: ctx.runtime.workspaceRoot,
          productRoot: ctx.runtime.productRoot,
          schemaRoot: ctx.runtime.schemaRoot,
          exitCode: 0,
        },
      };
    },
    async productTemplate(ctx) {
      const templatesDir = String(ctx.product.templatesDir ?? './product/templates').replace(/^\\.\\//, '');
      const manifests = await ctx.tools.fs.glob(\`\${templatesDir}/**/template.json\`);
      const snapshots = [];
      for (const path of manifests) {
        snapshots.push({
          path,
          manifest: await ctx.tools.fs.readJson(path),
        });
      }
      await ctx.tools.fs.writeJson('.lania/reports/product-templates.json', { templatesDir, manifests: snapshots }, { space: 2 });
      return {
        result: {
          templateId: '${escapeTemplateString(input.templateId)}',
          templateTitle: '${escapeTemplateString(input.templateTitle)}',
          templatesCount: Array.isArray(manifests) ? manifests.length : 0,
          output: '.lania/reports/product-templates.json',
          exitCode: 0,
        },
      };
    },
  },
  templates: [
    {
      id: '${escapeTemplateString(input.templateId)}',
      title: '${escapeTemplateString(input.templateTitle)}',
    },
  ],
};
`;
}
