/**
 * publish handler 使用的一组“解析与默认值推导”辅助函数。
 *
 * 这些 helper 的职责很单一：
 * - 从 params / productConfig / package.json 中抽取发布所需字段
 * - 统一默认值与回退顺序
 * - 把零散输入整理成 manifest 更容易消费的结构
 *
 * 这样真正的 publish 主逻辑可以专注于 staging、manifest 生成和执行。
 */
import { resolve } from 'node:path';

import type { ProductBundlePlatformTarball, ProductPublishManifestPackage } from '../types.js';
import { firstNonEmptyString } from '../utils.js';

export function resolvePublishDistTag(params: Record<string, unknown>, packageVersion: string): string {
  // dist-tag 优先从显式参数取；如果没给，再根据 prerelease 版本自动推断。
  const fromParams = firstNonEmptyString(params.distTag, params['dist-tag'], params.channel);
  if (fromParams) {
    return fromParams;
  }
  // 预发布版本（例如 `1.2.3-next.0`）默认把 prerelease label 当作 dist-tag。
  const prereleaseLabel = packageVersion.split('-', 2)[1]?.split('.', 1)[0]?.trim();
  if (prereleaseLabel && /^[A-Za-z0-9._-]+$/.test(prereleaseLabel)) {
    return prereleaseLabel;
  }
  return 'latest';
}

export function resolvePublishChannel(params: Record<string, unknown>, distTag: string): string {
  return firstNonEmptyString(params.channel, params.distTag, params['dist-tag']) ?? distTag;
}

export function resolvePublishRegistry(params: Record<string, unknown>): string {
  // registry 优先级：显式参数 -> npm 环境变量 -> 官方默认 registry。
  return (
    firstNonEmptyString(params.registry, process.env.npm_config_registry) ??
    'https://registry.npmjs.org/'
  );
}

export function resolvePublishAccess(_params: Record<string, unknown>): 'public' {
  // 当前发布规划统一走 public；如果后面支持 private/internal，这里会是集中扩展点。
  return 'public';
}

export function resolvePublishPackageName(
  productConfig: Record<string, unknown>,
  sourcePackageJson: Record<string, unknown>,
): string {
  // 包名优先从 product 配置取，其次回退到源 package.json，再最后构造一个稳定默认值。
  const fromProduct = typeof productConfig.name === 'string' ? productConfig.name.trim() : '';
  if (fromProduct) {
    return fromProduct;
  }
  const fromPackage =
    typeof sourcePackageJson.name === 'string' ? sourcePackageJson.name.trim() : '';
  if (fromPackage) {
    return fromPackage;
  }
  const binaryName =
    typeof productConfig.binaryName === 'string' && productConfig.binaryName.trim().length > 0
      ? productConfig.binaryName.trim()
      : 'product';
  return `@lania-product/${binaryName}`;
}

export function resolvePublishPackageVersion(
  productConfig: Record<string, unknown>,
  sourcePackageJson: Record<string, unknown>,
): string {
  // 版本号没有复杂推导，只有“product 优先，package.json 其次，最后回退 0.1.0”。
  const fromProduct = typeof productConfig.version === 'string' ? productConfig.version.trim() : '';
  if (fromProduct) {
    return fromProduct;
  }
  const fromPackage =
    typeof sourcePackageJson.version === 'string' ? sourcePackageJson.version.trim() : '';
  return fromPackage || '0.1.0';
}

export function createPublishedReadme(input: {
  packageName: string;
  binaryName: string;
  version: string;
}): string {
  // publish 产物默认生成一个极简 README，至少说明包名、版本和最基础使用方式。
  return `# ${input.packageName}

Version: ${input.version}

This package is a publish-ready product artifact generated by \`lan product publish\`.

Usage:

\`\`\`bash
npm install ${input.packageName}
npx ${input.binaryName} --help
\`\`\`
`;
}

export function resolveExecutionTarballPath(cwd: string, rawTarball: string): string {
  // manifest 里的 tarball 路径通常写成 `./...`，这里统一按执行根目录解析成绝对路径。
  return resolve(cwd, rawTarball.replace(/^\.\//, ''));
}

export function createRegistryManifestPackages(input: {
  packageName: string;
  packageVersion: string;
  productTarball: string;
  cliTarball: string | null;
  cliPackageVersion: string;
  platformTarballs: ProductBundlePlatformTarball[];
  distTag: string;
  channel: string;
}): ProductPublishManifestPackage[] {
  // 把 product / official cli / platform binaries 三类 tarball 统一整理成 manifest package 列表。
  const packages: ProductPublishManifestPackage[] = [
    {
      role: 'product',
      name: input.packageName,
      version: input.packageVersion,
      tarball: input.productTarball,
      distTag: input.distTag,
      channel: input.channel,
      publishStrategy: 'npm_tarball_publish',
    },
  ];
  if (input.cliTarball) {
    packages.push({
      role: 'official_cli',
      name: '@lania-cli/cli',
      version: input.cliPackageVersion,
      tarball: input.cliTarball,
      distTag: input.distTag,
      channel: input.channel,
      publishStrategy: 'npm_tarball_publish',
    });
  }
  for (const entry of input.platformTarballs) {
    packages.push({
      role: 'platform_binary',
      name: entry.packageName,
      version: entry.version,
      tarball: entry.tarball,
      distTag: input.distTag,
      channel: input.channel,
      publishStrategy: 'npm_tarball_publish',
      optional: true,
      platform: entry.platform,
      source: entry.source,
    });
  }
  return packages;
}
