use std::path::Path;

use anyhow::Result;

use crate::generate_schema::{render_contract_go, render_transport_go};
use crate::generate_types::{CompiledContractEntry, GeneratedContractPlan};
use crate::models::{GenerateApiMode, GenerateApiWorkflowInput};

pub(crate) fn render_contract_entry(
    entry: &CompiledContractEntry,
    contract_dir: &Path,
    transport_dir: &Path,
) -> Result<Vec<GeneratedContractPlan>> {
    let mut plans = vec![GeneratedContractPlan {
        path: contract_dir.join(format!("{}.contract.gen.go", entry.slug)),
        content: render_contract_go(entry),
        owner: Some(entry.name.clone()),
    }];
    for target in &entry.targets {
        plans.push(GeneratedContractPlan {
            path: transport_dir
                .join(target)
                .join(format!("{}_{}.gen.go", entry.slug, target)),
            content: render_transport_go(entry, target)?,
            owner: Some(entry.name.clone()),
        });
    }
    Ok(plans)
}

pub(crate) fn render_module_file(
    entries: &[CompiledContractEntry],
    module_file: &Path,
) -> GeneratedContractPlan {
    let mut body = String::from("// Code generated by lania generate api. DO NOT EDIT.\n\n");
    body.push_str("package modules\n\n");
    body.push_str("var GeneratedContracts = []string{\n");
    for entry in entries {
        body.push_str(&format!("    \"{}\",\n", entry.name));
    }
    body.push_str("}\n\n");
    body.push_str("var GeneratedTargets = map[string][]string{\n");
    for entry in entries {
        let targets = entry
            .targets
            .iter()
            .map(|target| format!("\"{target}\""))
            .collect::<Vec<_>>()
            .join(", ");
        body.push_str(&format!("    \"{}\": {{{targets}}},\n", entry.name));
    }
    body.push_str("}\n");

    GeneratedContractPlan {
        path: module_file.to_path_buf(),
        content: body,
        owner: None,
    }
}

pub(crate) fn render_generate_command_plan(
    config_path: &Path,
    input: &GenerateApiWorkflowInput,
) -> Vec<String> {
    let mut command = vec!["generate".into(), "api".into()];
    match input.mode {
        GenerateApiMode::Plan => command.push("plan".into()),
        GenerateApiMode::Diff => command.push("diff".into()),
        GenerateApiMode::Init => command.push("init".into()),
        GenerateApiMode::Apply => {}
    }
    command.push("--config".into());
    command.push(config_path.display().to_string());
    if !input.source_filter.is_empty() {
        command.push("--source".into());
        command.push(input.source_filter.join(","));
    }
    if !input.target_filter.is_empty() {
        command.push("--target".into());
        command.push(input.target_filter.join(","));
    }
    if !input.entry_filter.is_empty() {
        command.push("--entry".into());
        command.push(input.entry_filter.join(","));
    }
    if input.check {
        command.push("--check".into());
    }
    if input.clean {
        command.push("--clean".into());
    }
    if input.dry_run {
        command.push("--dry-run".into());
    }
    if input.force {
        command.push("--force".into());
    }
    command
}
